### ISSUE TITLE
git clone git@github.com:TVVT/Projects.git 不可用

### ISSUE THREAD

**Issue by theseusyang** [TVVT/Zero#54]
git clone git@github.com:TVVT/Projects.git  下载不了此工程。

请问在没有Projects项目的情况下，怎么使用 Zero？谢谢！

**Comment by kevin14** [comment]
@theseusyang  hi，目前我们没有在zero里做过项目的初始化功能，你可以clone git@github.com:TVVT/projects.git这个项目用起来。

**Comment by theseusyang** [comment]
好的，非常感谢！
